Repository Iteatime/Acrabadabra, pull requests merged in 2019-04, with the labels that each got.

#83 Unit tests on deploy
  .circleci/config.yml
  README.md
  package-lock.json
  package.json
  scripts/ci-validate.js
  scripts/config/karma-phantom.conf.js
Labels: need review

#84 feat(app): add a notification system
  e2e/features/notification.feature
  src/app/app.module.ts
  src/app/components/app/app.component.html
  src/app/modules/notification/@type/notification-options.ts
  src/app/modules/notification/@type/notification.ts
  src/app/modules/notification/components/notifications/notifications.component.html
  src/app/modules/notification/components/notifications/notifications.component.scss
  src/app/modules/notification/components/notifications/notifications.component.ts
  src/app/modules/notification/notification.module.ts
  src/app/modules/notification/services/notification.service.spec.ts
  src/app/modules/notification/services/notification.service.ts
  src/app/modules/timesheet/components/timesheet-edit/timesheet-edit.component.html
  src/app/modules/timesheet/components/timesheet-edit/timesheet-edit.component.scss
  src/app/modules/timesheet/components/timesheet-edit/timesheet-edit.component.ts
  src/app/modules/timesheet/services/timesheet.service.spec.ts
  src/app/shared/directives/copy-to-clipboard/copy-to-clipboard.directive.spec.ts
  src/app/shared/directives/copy-to-clipboard/copy-to-clipboard.directive.ts
Labels: need review

#92 HotFix Make the Circle CI job fail on test error
  .circleci/config.yml
  scripts/ci-validate.js
Labels: need review

#91 HotFix better gherkin
  e2e/features/I_receive_a_notification.feature
  e2e/features/enter_a_flat_fee_expense.feature
  e2e/features/enter_a_mileage_expense.feature
  e2e/features/enter_a_misc_expense.feature
  e2e/features/enter_an_invoice.feature
  e2e/features/enter_my_activity_report.feature
  e2e/features/notification.feature
  e2e/features/review_an_activity_report.feature
Labels: need review

#74 Provider authentication identity
  angular.json
  package-lock.json
  package.json
  scripts/set-env.js
  src/app/components/header/header.component.html
  src/app/components/header/header.component.scss
  src/app/components/header/header.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.scss
  src/app/components/home/home.component.ts
  src/app/modules/timesheet/components/timesheet-edit/timesheet-edit.component.ts
  src/app/modules/timesheet/timesheet.routes.ts
  src/app/shared/services/authentication/authentication.service.spec.ts
  src/app/shared/services/authentication/authentication.service.ts
  src/app/style/_vars.scss
Labels: Reviewed

#98 feat(app): unvalid shared timesheet
  src/app/modules/timesheet/components/timesheet-edit/timesheet-edit.component.ts
Labels: Reviewed

#101 HeaderComponent: Change the login button
  package-lock.json
  src/app/components/header/header.component.html
  src/app/components/header/header.component.scss
Labels: To merge

#102 Mkanel add optional tag fields
  e2e/features/enter_an_invoice.feature
  src/app/modules/timesheet/components/invoice-form/invoice-form.component.html
  src/app/modules/timesheet/components/invoice-form/invoice-form.component.scss
Labels: Reviewed

#103 add client infos with timesheet transfer
  e2e/features/invoice_my_timesheet.feature
  src/app/modules/timesheet/services/timesheet.service.spec.ts
  src/app/modules/timesheet/services/timesheet.service.ts
Labels: Reviewed
